language: rust

rust:
  - 1.20.0
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

script:
  - cd pcsc-sys && cargo build --verbose
  - cd ../pcsc && cargo build --verbose
  - cd ../pcsc-sys && if [[ $TRAVIS_RUST_VERSION == stable ]]; then cargo clippy --verbose; fi
  - cd ../pcsc && if [[ $TRAVIS_RUST_VERSION == stable ]]; then cargo clippy --verbose; fi
  - cd ../pcsc-sys && cargo test --verbose
  - cd ../pcsc && cargo test --verbose

cache: cargo

addons:
  apt:
    packages:
      - libpcsclite-dev
