environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: stable
    - TARGET: i686-pc-windows-msvc
      TOOLCHAIN: stable
install:
  - set PATH=%PATH%;C:\Program Files\Git\mingw64\bin
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %TOOLCHAIN%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cd pcsc-sys && cargo build --verbose
  - cd ../pcsc && cargo build --verbose
  - cd ../pcsc && cargo test --verbose
