environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      TOOLCHAIN: stable
    - TARGET: i686-pc-windows-msvc
      TOOLCHAIN: stable
install:
  - ps: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
  - ps: Start-FileDownload https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %TOOLCHAIN%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cd pcsc-sys && cargo build --verbose
  - cd ../pcsc && cargo build --verbose
  - cd ../pcsc && cargo test --verbose
